listaligada: clear
	@echo "========================================="
	@echo "		AJUDA		"
	@echo "========================================="
	@echo "Compilando a lista ligada"
	@gcc main.c listaligada.c log.c -o listaligada
	@echo "Tornando o programa olamundo executável"
	@chmod +x listaligada
	@echo "Execuando o programa olamundo executável"
	@./listaligada
	@echo "========================================="
clear:
	@echo "========================================="
	@echo "Removendo os programas compilados"
	@echo "========================================="
	@echo "Removendo o programa da lista ligada"
	rm -f listaligada
	@echo "========================================="
help:
	@echo "==================="
	@echo "      AJUDA        "
	@echo "==================="
	@echo "help 		|ajuda"
	@echo "listaligada 	|executa mensagem de teste"
	@echo "clear		|apaga códigos compilados"	