Listageneralizada: clear
	@echo "========================================="
	@echo "		AJUDA		"
	@echo "========================================="
	@echo "Compilando a lista generalizada"
	@gcc "Lista Generalizada"/main.c "Lista Generalizada"/Listageneralizada.c "Lista Generalizada"/log.c -o Listageneralizada
	@echo "Tornando a Lista generalizada"
	@chmod +x Listageneralizada
	@echo "Execuando a Lista generalizada"
	@./Listageneralizada
	@echo "========================================="
Doublelist: clear
	@echo "========================================="
	@echo "		AJUDA		"
	@echo "========================================="
	@echo "Compilando a lista duplamente ligada"
	@gcc DoubleList/main.c DoubleList/doublelist.c DoubleList/log.c -o ListaDupla
	@echo "Tornando a Lista Dupla executável"
	@chmod +x ListaDupla
	@echo "Execuando a Lista Dupla executável"
	@./ListaDupla
	@echo "========================================="
clear:
	@echo "========================================="
	@echo "Removendo os programas compilados"
	@echo "========================================="
	@echo "Removendo o programa da Lista Dupla"
	rm -f Doublelist
	@echo "========================================="
help:
	@echo "==================="
	@echo "      AJUDA        "
	@echo "==================="
	@echo "help 		|ajuda"
	@echo "ListaDupla 	|executa mensagem de teste"
	@echo "clear		|apaga códigos compilados"	